### Register a user POST /AUTH/REGISTER
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "username": "arzi2",
  "password": "123"
}

### Login a user POST /AUTH/LOGIN
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "username": "arzi2",
  "password": "123"
}
